### ISSUE TITLE
v2.0.11 does not load UI menus on Mac OS and Windows

### ISSUE THREAD

**Issue by astrochun** [APTrust/dart#421] opened 2021-03-11 22:20 UTC
This is a great tool that our organization is now thinking of using for data preservation.

We attempted to install and run DART v2.0.11 locally on our machines. However, when we launched DART, the UI is all white without any menus, etc. This is occurring for multiple operating systems.

Operating systems details:
Windows:
 - Windows 10 education, Version 10.0.19042 Build 19042
 - Windows 10 Enterprise version 2004 build 19041.804

macOS:
 - Mojave (10.14.6)
 - Big Sur (11.2.2)
 
Note that we used the .dmg and .exe available through the README.md
 
We did tried earlier versions and those were successful:
- v2.0.4 did work with all four testing environments
- v2.0.9 appear to the be last version that worked on one of the Windows machines

**Comment by diamondap** [comment] 2021-03-12 14:28
I can replicate the problem. It's caused by changes to the security model in Electron v 12.0.0, as described in this issue: https://github.com/electron/electron/issues/23506. Working on a fix...

**Comment by astrochun** [comment] 2021-03-12 14:32
> I can replicate the problem. It's caused by changes to the security model in Electron v 12.0.0, as described in this issue: [electron/electron#23506](https://github.com/electron/electron/issues/23506). Working on a fix...

Thanks for the quick update. We can use old versions in the mean time as we are testing it for our needs, so the newest features are not as critical.

**Comment by diamondap** [comment] 2021-03-12 15:15
This works locally, but I'm waiting to test packaged builds before closing this. To work properly with Electron 12.0.0, we'll need to follow these guidelines (which currently don't work):

https://github.com/electron/electron/blob/master/docs/tutorial/context-isolation.md
https://github.com/electron/electron/blob/master/docs/api/context-bridge.md
https://github.com/reZach/secure-electron-template/blob/master/app/electron/preload.js

Recent attempts show the preload script + context bridge does not expose objects or functions, and does not report failed attempts to expose items. So, for now, we stick with Electron 11.3.0.

**Comment by diamondap** [comment] 2021-03-12 15:42
@astrochun The Windows version is now fixed, if you want to try downloading again from https://s3.amazonaws.com/aptrust.public.download/DART/DART+Setup+2.0.11.exe

The Mac version will take a little longer because we need to renew our Apple developer certificate.

**Comment by diamondap** [comment] 2021-03-15 15:05
For now, please use v 2.0.11 for Windows and 2.0.10 for Mac and Linux. We're having trouble renewing our MacOS distribution certificate, but we hope to resolve that soon. 

Windows: https://s3.amazonaws.com/aptrust.public.download/DART/DART+Setup+2.0.11.exe
Mac: https://s3.amazonaws.com/aptrust.public.download/DART/DART-2.0.10.dmg
Linux: https://s3.amazonaws.com/aptrust.public.download/DART/DART_2.0.10_amd64.deb

**Comment by astrochun** [comment] 2021-03-15 15:07
> @astrochun The Windows version is now fixed, if you want to try downloading again from https://s3.amazonaws.com/aptrust.public.download/DART/DART+Setup+2.0.11.exe
> 
> The Mac version will take a little longer because we need to renew our Apple developer certificate.

Hi @diamondap. Sounds good. I just saw the README.md updated and just tested v2.0.10. Do you want me to close this issue since this is to be resolved soon?

**Comment by zoidy** [comment] 2021-03-15 15:22
The fixed Windows version 2.0.11 is working now, thank you

**Comment by diamondap** [comment] 2021-03-15 15:38
@astrochun Thanks. I'll close this when we have our new certificate set up. That may take a few days, but I do want to run both automated and manual tests on the new build before closing.

**Comment by diamondap** [comment] 2021-03-17 12:40
@astrochun This should be fixed. Try downloading again from https://s3.amazonaws.com/aptrust.public.download/DART/DART-2.0.11.dmg

**Comment by astrochun** [comment] 2021-03-17 16:30
> @astrochun This should be fixed. Try downloading again from https://s3.amazonaws.com/aptrust.public.download/DART/DART-2.0.11.dmg

Confirming that it works with one of our Macs the we listed above. You resolved this issue; Feel free to close this issue when your unit and manual tests pass.

**Comment by diamondap** [comment] 2021-03-17 17:05
Fixed in commit https://github.com/APTrust/dart/commit/c1d39c64121a5db9f3ebd7fc05c8acdfbe5740d6. Mac builds are working again with new developer certificate. Closing.

**Closed by diamondap** 2021-03-17 17:05 UTC
