### ISSUE TITLE
Display Error in dart 2.0.11 on Ubuntu 20.10

### ISSUE THREAD

**Issue by klighty** [APTrust/dart#429] opened 2021-04-08 23:12 UTC
Hello, just posting here to report an error that I came across while attempting to get DART working on a virutal linux (Ubuntu 20.10 amd64 lts) installation. When installing the 2.0.11 version of DART, the main window has display errors when launched that did not allow me any access to workflow or jobs via the GUI. Rolling back to 2.0.10, the issues were not present and the program worked as expected.

**Comment by diamondap** [comment] 2021-04-12 13:39
Sorry for the late reply. I was away.

This issue had affected DART 2.0.11 on Mac, Windows, and Linux. It's fixed on Mac and Windows, and should have been fixed on Linux. I'll take a look within the next 24 hours, when I have access to an Ubuntu machine.

**Comment by diamondap** [comment] 2021-04-12 21:42
This is actually the same as https://github.com/APTrust/dart/issues/421. Unfortunately, the new Mac and Linux builds didn't make it to S3 for public download. This is due to some configuration problems with our build server. We're working on this and hope to have it resolved in the next few days.

**Comment by diamondap** [comment] 2021-04-13 21:57
@klighty  This should be fixed. I confirmed that I can run jobs with both the Linux and Mac versions. If you can confirm, I'll close this. You can get the new Linux build at https://s3.amazonaws.com/aptrust.public.download/DART/DART_2.0.11_amd64.deb

**Comment by klighty** [comment] 2021-04-29 19:21
I apologize for my delayed response. I can confirm that the new build seems to be working just fine! Thank you.

**Comment by diamondap** [comment] 2021-04-29 19:55
Thanks. Glad that fixed it.

**Closed by diamondap** 2021-04-29 19:55 UTC
